set(WGPARTSBASEDDETECTOR_DIR "${BR_THIRD_PARTY_DIR}/PartsBasedDetector")
mark_as_advanced(WGPARTSBASEDDETECTOR_DIR)
#set(git "git")
#if(NOT EXISTS ${WGPARTSBASEDDETECTOR_DIR})
#    # download the source from github
#    set(git_cmd "clone")
#    set(git_arg "https://github.com/wg-perception/PartsBasedDetector.git")
#    execute_process(COMMAND ${git} ${git_cmd} ${git_arg} WORKING_DIRECTORY ${BR_THIRD_PARTY_DIR})
#    set(git_cmd "submodule")
#    set(git_arg "init")
#    execute_process(COMMAND ${git} ${git_cmd} ${git_arg} WORKING_DIRECTORY ${WGPARTSBASEDDETECTOR_DIR})
#    set(git_arg "update")
#    execute_process(COMMAND ${git} ${git_cmd} ${git_arg} WORKING_DIRECTORY ${WGPARTSBASEDDETECTOR_DIR})
#else()
#    # update the source and model files
#    set(git_cmd "pull")
#    execute_process(COMMAND ${git} ${git_cmd} WORKING_DIRECTORY ${WGPARTSBASEDDETECTOR_DIR})
#    set(git_cmd "submodule")
#    set(git_arg "update")
#    execute_process(COMMAND ${git} ${git_cmd} ${git_arg} WORKING_DIRECTORY ${WGPARTSBASEDDETECTOR_DIR})
#endif()
file(COPY "${WGPARTSBASEDDETECTOR_DIR}/models/" DESTINATION "${BR_SHARE_DIR}/models/PartsBasedDetector")

add_subdirectory(${WGPARTSBASEDDETECTOR_DIR} ${WGPARTSBASEDDETECTOR_DIR}/build)
include_directories(${WGPARTSBASEDDETECTOR_DIR}/include)
set(WGPARTSBASEDDETECTOR_LIBS PartsBasedDetector_lib)
